### PR TITLE
Add a script to create VirtualBox VM.

### PR DESCRIPTION
**Pull request by yungyuc**
The script uses VirtualBox's command line tool VBoxManage to create and specify the VM settings.

### CODE REVIEW

**Comment by yungyuc** [comment]
@tjwei @jjhuang314 The script creates the VM but doesn't install OS in it.  We still need to manually finish the OS installation.  After Ubuntu is installed and configured with ssh, we can use an automated tool to finish the image preparation.  The ansible script should be ported later.

I will merge this no later than one day.

**Comment by tjwei** [comment]
Why not use vagrant and then export to a VirtualBox VM? 
Is this the method that we used for the 2nd cython workshop?

**Comment by yungyuc** [comment]
Yes we can.  What a blind spot :)  But there might be some settings that vagrant doesn't do.  We can use VBoxManage for them.

I don't know how @jjhuang314 and @jminh did for the VM of 2nd cython up.

**Comment by alberthuang2718** [comment]
We installed Ubuntu from scratch in VirtualBox. As far as I know, VirtualBox images in vagrant are mostly for server without GUI environments. So I think VBoxManage scripts can change settings on the VirtualBox image we created or will create.

**Comment by yungyuc** [comment]
I am working on vagrant script that adds GUI and customizes other settings to the VM.  I will make an PR later today.

**Comment by tjwei** [comment]
this might be helpful
http://codingbee.net/tutorials/vagrant-tutorials/vagrant-enabling-a-vms-gui-mode/

**Pull request closed without merging**
